// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Testcase1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testcase1() {
    driver.get("https://crm.geekbrains.space/user/login");
    driver.manage().window().setSize(new Dimension(1440, 807));
    driver.findElement(By.id("prependedInput")).sendKeys("Applanatest1");
    driver.findElement(By.id("prependedInput2")).click();
    driver.findElement(By.id("prependedInput2")).sendKeys("Student2020!");
    driver.findElement(By.id("_submit")).click();
    driver.findElement(By.cssSelector(".dropdown:nth-child(3) .single:nth-child(4) .title")).click();
    driver.findElement(By.linkText("Создать проект")).click();
    driver.findElement(By.name("crm_project[name]")).sendKeys("Мой проект 01");
    driver.findElement(By.cssSelector(".lang-ru")).click();
    driver.findElement(By.cssSelector(".select2-default > .select2-chosen")).click();
    driver.findElement(By.xpath("//*[@id=\"select2-drop\"]/ul[2]/li[2]/div")).click();
    driver.findElement(By.cssSelector(".lang-ru")).click();
    driver.findElement(By.cssSelector("#s2id_crm_project_contactMain-uid-60ae2171a624d .select2-arrow")).click();
    driver.findElement(By.xpath("//*[@id=\"select2-drop\"]/ul[2]/li[2]/div")).click();
    driver.findElement(By.cssSelector(".lang-ru")).click();
    driver.findElement(By.xpath("//*[@id=\"crm_project_businessUnit-uid-60ae228d7d245\"]")).click();
    {
      WebElement dropdown = driver.findElement(By.id("crm_project_businessUnit-uid-60ae276fb333f"));
      dropdown.findElement(By.xpath("//option[. = 'Research & Development']")).click();
    }
    driver.findElement(By.xpath("//*[@id=\"crm_project_curator-uid-60ae276fd8d72\"]")).click();
    {
      WebElement dropdown = driver.findElement(By.id("crm_project_curator-uid-60ae276fd8d72"));
      dropdown.findElement(By.xpath("//option[. = 'Applanatest Applanatest Applanatest']")).click();
    }
    driver.findElement(By.xpath("//*[@id=\"crm_project_rp-uid-60ae276fcfaf4\"]")).click();
    {
      WebElement dropdown = driver.findElement(By.id("crm_project_rp-uid-60ae21dcc141b"));
      dropdown.findElement(By.xpath("//option[. = 'Applanatest Applanatest Applanatest']")).click();
    }
    driver.findElement(By.xpath("//*[@id=\"crm_project_administrator-uid-60ae276fa7da8\"]")).click();
    {
      WebElement dropdown = driver.findElement(By.id("crm_project_administrator-uid-60ae21dc99c7e"));
      dropdown.findElement(By.xpath("//option[. = 'Applanatest Applanatest Applanatest']")).click();
    }
    driver.findElement(By.id("crm_project_manager-uid-60ae2a6a51d9d")).click();
    {
      WebElement dropdown = driver.findElement(By.id("crm_project_manager-uid-60ae2a6a51d9d"));
      dropdown.findElement(By.xpath("//option[. = 'Applanatest Applanatest Applanatest']")).click();
    }
    driver.findElement(By.cssSelector(".btn-group:nth-child(4) > .btn")).click();
  }
}
